version: '3.8'

services:
  docker-server:
    image: jhimjhim/springbootmysql:latest
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/shop_manager?autoReconnect=true&useSSL=false
    depends_on:
      docker-mysql:
        condition: service_healthy  
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=U+yW56N*HK6Efy2@
      - MYSQL_DATABASE=shop_manager
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost","-uroot","-pU+yW56N*HK6Efy2@"]
            timeout: 10s
            retries: 10  
    ports:
      - 3307:3306
  front:
    image : jhimjhim/shop_client
    links:
      - "docker-server"
    depends_on:
      - "docker-server"
    ports:
      - "4200:80"



