name: Docker Image CI

on:
  workflow_dispatch:
  push:
  pull_request:
env:
  USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
          services: docker-mysql
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: jhimjhim/springbootmysql
          add-hosts: host.docker.internal:172.17.0.1
          network: host